spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://8.136.81.197:3306/xue_gao?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 20
      min-idle: 50
      max-active: 1000
  mvc:
     pathmatch:
       matching-strategy: ANT_PATH_MATCHER

